'use client'

import { useQuery } from 'convex/react'
import { Download } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Bar, BarChart, CartesianGrid, LabelList, Tooltip, XAxis } from 'recharts'
import { DashboardShell } from '@/components/shell'
import { Card } from '@/components/ui/card'
import { ChartContainer } from '@/components/ui/chart'
import { Button } from '@/components/ui/button'
import { Select } from '@/components/ui/select'
import { Table, TableWrap, Td, Th } from '@/components/ui/table'
import { useAuthArgs, useBackendAvailable } from '@/components/providers'
import { api, type AnalyticsDashboard } from '@/lib/convex'
import { downloadAnalyticsPdf, type AnalyticsReportType } from '@/lib/analytics-pdf'

type TimeWindow = 'morning' | 'afternoon' | 'evening' | 'overtime' | 'full'
type ChartDatum = { label: string; orders: number; revenueKes: number }
const ranges: Record<Exclude<TimeWindow, 'full'>, number[]> = { morning: [6, 7, 8, 9, 10, 11], afternoon: [12, 13, 14, 15, 16], evening: [17, 18, 19, 20, 21], overtime: [22, 23, 0, 1, 2, 3, 4, 5] }
const pad = (hour: number) => String(hour).padStart(2, '0')
function buildChartData(hours: Array<{ hour: number; orders: number; revenueKes: number }>, window: TimeWindow): ChartDatum[] {
  const byHour = new Map(hours.map((entry) => [entry.hour, entry])); const at = (hour: number) => byHour.get(hour) ?? { hour, orders: 0, revenueKes: 0 }
  if (window === 'full') return Array.from({ length: 8 }, (_, index) => { const start = index * 3; const slice = [start, start + 1, start + 2].map(at); return { label: `${pad(start)}–${pad(start + 3)}`, orders: slice.reduce((sum, entry) => sum + entry.orders, 0), revenueKes: slice.reduce((sum, entry) => sum + entry.revenueKes, 0) } })
  return ranges[window].map((hour) => { const entry = at(hour); return { label: `${pad(hour)}:00`, orders: entry.orders, revenueKes: entry.revenueKes } })
}
function OrdersTooltip({ active, payload }: { active?: boolean; payload?: Array<{ payload: ChartDatum }> }) { if (!active || !payload?.length) return null; const datum = payload[0]!.payload; return <div className="chart-tip"><p className="chart-tip-label">{datum.label}</p><p><strong>{datum.orders}</strong> {datum.orders === 1 ? 'order' : 'orders'}</p><p className="fine-print muted">KES {datum.revenueKes.toLocaleString()}</p></div> }
const demoAnalytics: AnalyticsDashboard = { windows: { today: { from: Date.now() - 12 * 60 * 60_000, to: Date.now() }, last7Days: { from: Date.now() - 7 * 24 * 60 * 60_000, to: Date.now() } }, today: { orders: 87, revenueKes: 48_620, averageOrderValueKes: 559 }, topItems: [{ itemId: '1', name: 'Chicken biryani', quantity: 52, orderCount: 46 }, { itemId: '2', name: 'Beef stew', quantity: 43, orderCount: 39 }, { itemId: '3', name: 'Chapati', quantity: 72, orderCount: 36 }], ordersByHour: [{ hour: 10, orders: 7, revenueKes: 4_100 }, { hour: 11, orders: 12, revenueKes: 6_800 }, { hour: 12, orders: 24, revenueKes: 13_400 }, { hour: 13, orders: 31, revenueKes: 18_200 }], tables: [{ tableNumber: 7, orders: 31, revenueKes: 18_420, medianTurnaroundMs: 21 * 60_000 }], waiters: [{ waiterId: '1', name: 'Mary Njeri', ordersServed: 42, medianServeTimeMs: 17 * 60_000, meanRating: 4.7, ratingCount: 31, tableNumbers: [1, 2, 5] }], lowestRatedItems: [{ itemId: '5', name: 'Fresh passion juice', meanRating: 3.1, ratingCount: 8, comments: ['Took too long', 'Not cold enough'] }], offers: { activeItems: 3, offerOrders: 18, offerUnits: 24, discountKes: 3_200, revenueKes: 14_800, normalOrders: 69, normalRevenueKes: 33_820, items: [{ itemId: '1', name: 'Chicken Fried Rice Bowl', offerLabel: 'Weekly offer', offerPriceKes: 750, originalPriceKes: 850, units: 12, discountKes: 1_200, revenueKes: 9_000 }] } }
function minutes(value: number | null) { return value === null ? '—' : `${Math.round(value / 60_000)} min` }

export function ManagerAnalytics() {
  const backend = useBackendAvailable(); const auth = useAuthArgs(); const result = useQuery(api.analytics.dashboard, backend ? auth! : 'skip'); const data = result ?? (backend ? null : demoAnalytics); const [hourWindow, setHourWindow] = useState<TimeWindow>('full'); const [reportType, setReportType] = useState<AnalyticsReportType>('full')
  const chartData = useMemo(() => buildChartData(data?.ordersByHour ?? [], hourWindow), [data?.ordersByHour, hourWindow])
  if (!data) return <DashboardShell section="Analytics"><section className="page-section"><p className="muted">Loading live analytics…</p></section></DashboardShell>
  const totalComparedOrders = data.offers.offerOrders + data.offers.normalOrders; const offerShare = totalComparedOrders ? Math.round((data.offers.offerOrders / totalComparedOrders) * 100) : 0
  return <DashboardShell section="Analytics" actions={<div className="analytics-report-actions"><Select aria-label="Report type" value={reportType} onChange={(event) => setReportType(event.target.value as AnalyticsReportType)}><option value="full">Full report</option><option value="offers">Offers report</option><option value="staff">Staff report</option></Select><Button size="small" onClick={() => void downloadAnalyticsPdf(data, reportType)}><Download size={15} /> Export PDF</Button></div>}>
    <section className="metric-grid" aria-label="Today’s headline metrics"><article className="metric-tile"><span className="caption">Orders today</span><strong className="metric-value">{data.today.orders}</strong><span className="fine-print">Since midnight</span></article><article className="metric-tile"><span className="caption">Revenue today</span><strong className="metric-value">KES {data.today.revenueKes.toLocaleString()}</strong><span className="fine-print">Settled only</span></article><article className="metric-tile"><span className="caption">Offer order share</span><strong className="metric-value">{offerShare}%</strong><span className="fine-print">Last 7 days</span></article></section>
    <section className="page-section"><div className="section-heading"><div><p className="caption">Live operating picture</p><h1>Restaurant performance</h1><p className="muted">Compare promotions with normal menu sales, then export the report you need.</p></div></div><div className="analytics-grid">
      <Card className="chart-card"><div className="chart-card-head"><div><h3>Orders by hour</h3><p className="fine-print muted">Last 7 days</p></div><Select className="chart-window-select" aria-label="Time window" value={hourWindow} onChange={(event) => setHourWindow(event.target.value as TimeWindow)}>{(['morning', 'afternoon', 'evening', 'overtime', 'full'] as TimeWindow[]).map((entry) => <option key={entry} value={entry}>{entry === 'full' ? 'Full time' : entry}</option>)}</Select></div><ChartContainer height={280}><BarChart accessibilityLayer data={chartData} margin={{ top: 24, right: 8, left: 8, bottom: 0 }}><CartesianGrid vertical={false} stroke="var(--hf-divider-soft)" /><XAxis dataKey="label" tickLine={false} axisLine={false} tickMargin={10} interval={0} tick={{ fontSize: 11, fill: 'var(--hf-ink-48)' }} /><Tooltip cursor={{ fill: 'rgba(0,0,0,.04)' }} content={<OrdersTooltip />} /><Bar dataKey="orders" fill="var(--hf-ink)" radius={[8, 8, 0, 0]} maxBarSize={56}><LabelList dataKey="orders" position="top" offset={10} fontSize={12} fill="var(--hf-ink)" /></Bar></BarChart></ChartContainer></Card>
      <Card><h3>Offers vs normal menu</h3><p className="fine-print muted">Last 7 days · offer-tagged order comparison</p><div className="offer-comparison-chart"><div><div className="offer-comparison-label"><span>Offer foods</span><strong>{data.offers.offerOrders} orders</strong></div><div className="offer-bar"><span style={{ width: `${totalComparedOrders ? (data.offers.offerOrders / totalComparedOrders) * 100 : 0}%` }} /></div><p className="fine-print muted">{data.offers.offerUnits} units · KES {data.offers.revenueKes.toLocaleString()} revenue</p></div><div><div className="offer-comparison-label"><span>Normal foods</span><strong>{data.offers.normalOrders} orders</strong></div><div className="offer-bar offer-bar-normal"><span style={{ width: `${totalComparedOrders ? (data.offers.normalOrders / totalComparedOrders) * 100 : 0}%` }} /></div><p className="fine-print muted">KES {data.offers.normalRevenueKes.toLocaleString()} revenue</p></div></div><p className="offer-analysis-note">{data.offers.offerOrders > data.offers.normalOrders ? 'Offers are currently driving more orders than normal menu items.' : 'Normal menu items currently drive more orders than offers.'}</p></Card>
      <Card><h3>Offer item performance</h3><p className="fine-print muted">Which offers sell best</p>{data.offers.items.length ? <TableWrap><Table><thead><tr><Th>Item</Th><Th>WAS → NOW</Th><Th>Units</Th></tr></thead><tbody>{data.offers.items.map((item) => <tr key={item.itemId}><Td><strong>{item.name}</strong><br /><span className="fine-print muted">{item.offerLabel} · save KES {item.discountKes.toLocaleString()}</span></Td><Td>KES {item.originalPriceKes.toLocaleString()} → KES {item.offerPriceKes.toLocaleString()}</Td><Td>{item.units}</Td></tr>)}</tbody></Table></TableWrap> : <p className="muted">No offer-tagged orders in this period.</p>}</Card>
      <Card><h3>Waiter performance</h3><p className="fine-print muted">Assigned tables and service outcomes · last 7 days</p><TableWrap><Table><thead><tr><Th>Waiter</Th><Th>Tables</Th><Th>Served</Th><Th>Median</Th></tr></thead><tbody>{data.waiters.map((entry) => <tr key={entry.waiterId}><Td>{entry.name}</Td><Td>{entry.tableNumbers.join(', ') || '—'}</Td><Td>{entry.ordersServed}</Td><Td>{minutes(entry.medianServeTimeMs)}</Td></tr>)}</tbody></Table></TableWrap></Card>
      <Card><h3>Top five items</h3><p className="fine-print muted">Order count · last 7 days</p><TableWrap><Table><thead><tr><Th>Item</Th><Th>Orders</Th></tr></thead><tbody>{data.topItems.map((item) => <tr key={item.itemId}><Td>{item.name}</Td><Td><strong>{item.orderCount}</strong></Td></tr>)}</tbody></Table></TableWrap></Card>
      <Card><h3>Table performance</h3><p className="fine-print muted">Orders and settled revenue · last 7 days</p><TableWrap><Table><thead><tr><Th>Table</Th><Th>Orders</Th><Th>Revenue</Th><Th>Median turn</Th></tr></thead><tbody>{data.tables.map((entry) => <tr key={entry.tableNumber}><Td>{entry.tableNumber}</Td><Td>{entry.orders}</Td><Td>KES {entry.revenueKes.toLocaleString()}</Td><Td>{minutes(entry.medianTurnaroundMs)}</Td></tr>)}</tbody></Table></TableWrap></Card>
    </div></section>
  </DashboardShell>
}
