packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20260722.1'
  - '@turbo/darwin-64@2.10.6'
  - '@turbo/darwin-arm64@2.10.6'
  - '@turbo/linux-64@2.10.6'
  - '@turbo/linux-arm64@2.10.6'
  - '@turbo/windows-64@2.10.6'
  - '@turbo/windows-arm64@2.10.6'
  - turbo@2.10.6

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
