'use client'

import Link from 'next/link'
import { useMutation, useQuery } from 'convex/react'
import { CheckCircle2, Download, Star } from 'lucide-react'
import { useSearchParams } from 'next/navigation'
import { useEffect, useState } from 'react'
import { useBackendAvailable } from '@/components/providers'
import { api } from '@/lib/convex'
import { downloadPaymentReceipt } from '@/lib/receipt'
import type { Order } from '@/lib/models'

export default function OrderCompletePage() {
  const backend = useBackendAvailable(); const searchParams = useSearchParams()
  const orderId = searchParams.get('orderId') ?? searchParams.get('order'); const reference = searchParams.get('trxref') ?? searchParams.get('reference')
  const details = useQuery(api.orders.paymentDetails, backend && orderId ? { orderId: orderId as never } : 'skip'); const submitFeedback = useMutation(api.feedback.submitWeb)
  const [message, setMessage] = useState('Confirming your payment…'); const [verified, setVerified] = useState(false); const [rating, setRating] = useState(0); const [comment, setComment] = useState(''); const [feedbackMessage, setFeedbackMessage] = useState(''); const [feedbackSubmitted, setFeedbackSubmitted] = useState(false)
  useEffect(() => { if (!reference || !orderId) { setMessage('Payment returned without an order reference. Please show the payment confirmation at the counter.'); return }; fetch(`/api/payments/paystack/verify?reference=${encodeURIComponent(reference)}&orderId=${encodeURIComponent(orderId)}`).then(async (response) => { const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error); setVerified(true); setMessage('Payment confirmed. Your order is now with the kitchen.') }).catch((error) => setMessage(error instanceof Error ? error.message : 'Payment could not be confirmed')) }, [orderId, reference])
  const receiptOrder = details ? { ...details, _id: details.orderId, source: 'web' as const, status: 'closed' as const } as Order : null
  const estimateMinutes = receiptOrder?.preparationMinutes ?? (receiptOrder ? Math.max(...receiptOrder.lines.map(() => 20), 20) : null)
  async function sendFeedback() { if (!receiptOrder || !rating || !backend || !details) return; setFeedbackMessage(''); try { await submitFeedback({ restaurantId: details.restaurantId, orderId: receiptOrder._id, rating, ...(comment.trim() ? { comment: comment.trim() } : {}) }); setFeedbackSubmitted(true) } catch (error) { setFeedbackMessage(error instanceof Error ? error.message : 'Feedback could not be submitted') } }
  return <main className="customer-success-page"><div className="customer-success-content"><div className="customer-success-mark"><CheckCircle2 size={34} strokeWidth={2.2} /></div><p className="caption">Heavenly Foods · Payment complete</p><h1>Payment successful</h1><p className="customer-success-message">{verified && estimateMinutes ? `Payment confirmed. Your meal will be ready in about ${estimateMinutes} minutes. The waiter will coordinate the individual items as they become ready.` : message}</p>{verified && receiptOrder && <><div className="customer-success-details"><div><span>Order</span><strong>{receiptOrder.reference ?? '—'}</strong></div><div><span>Table</span><strong>{receiptOrder.tableNumber}</strong></div><div><span>Total paid</span><strong>KES {receiptOrder.totalKes.toLocaleString()}</strong></div><div><span>Paystack reference</span><strong>{reference ?? receiptOrder.paystackReference ?? '—'}</strong></div></div><div className="payment-success-banner"><strong>Download your payment receipt</strong><p className="fine-print">Keep a copy of your payment confirmation.</p><div className="receipt-download-actions"><button className="button" onClick={() => void downloadPaymentReceipt(receiptOrder, reference ?? undefined)}><Download size={15} />Payment receipt</button><Link className="button button-secondary" href={`/order${receiptOrder.tableNumber ? `?table=${receiptOrder.tableNumber}` : ''}`}>Back to menu</Link></div></div><section className="customer-feedback"><p className="caption">Your experience</p><h2>Rate the service</h2>{feedbackSubmitted ? <p className="customer-feedback-thanks">Thank you for your feedback.</p> : <><div className="customer-rating-stars" role="radiogroup" aria-label="Rate the service from one to five stars">{[1, 2, 3, 4, 5].map((value) => <button key={value} type="button" role="radio" aria-checked={rating === value} aria-label={`${value} star${value === 1 ? '' : 's'}`} className={value <= rating ? 'selected' : ''} onClick={() => setRating(value)}><Star size={28} fill="currentColor" /></button>)}</div><textarea className="customer-feedback-comment" value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Leave a comment (optional)" rows={3} />{feedbackMessage && <p className="field-error" role="alert">{feedbackMessage}</p>}<button className="button customer-feedback-submit" type="button" disabled={!rating} onClick={() => void sendFeedback()}>Send feedback</button></>}</section></>}</div></main>
}
