name = "heavenly-foods-api"
main = "src/index.ts"
compatibility_date = "2026-07-01"
workers_dev = true

[observability]
enabled = true

[vars]
BUILD_SHA = "development"
FEEDBACK_DELAY_MS = "600000"

[triggers]
crons = ["* * * * *"]